### PR TITLE
require --force to push to remote gcrypt repo

### PR DESCRIPTION
**Pull request by jcolson**
Thank you for your interest in contributing to this project!

Please **do not** submit a pull request on GitHub.  This repository is
an automated mirror, and I don't develop using GitHub's platform.

Instead, please see CONTRIBUTING.md for patch submission info.

### CODE REVIEW

**Comment by jcolson** [comment]
was merged

**Comment by Myridium** [comment]
So this configuration option resolves this very serious long-standing bug... and you've opted to turn the option off by default? I don't understand.

**Comment by spwhitton** [comment]
Hello,

On Sun 21 Nov 2021 at 03:31PM -08, Myridium wrote:

> So this configuration option resolves this very serious long-standing
> bug... and you've opted to turn the option off by default? I don't
> understand.

I don't consider the bug resolved.  The option simply raises awareness
of it.

-- 
Sean Whitton

**Comment by Myridium** [comment]
> Hello,
> On Sun 21 Nov 2021 at 03:31PM -08, Myridium wrote: So this configuration option resolves this very serious long-standing bug... and you've opted to turn the option off by default? I don't understand.
> I don't consider the bug resolved. The option simply raises awareness of it.
> […](#)
> -- Sean Whitton

Hi Sean,

Sorry I'm a bit confused about what exactly this pull request resolves. Could you please clarify what exactly this option does?

Yesterday I tested your library and I found that my remote gcrypt server rejected my fast-forward push because it had commits which I did not have locally.

Isn't the big in your program supposed to be that this does *not* happen?

This was before I configured any git config.

**Comment by Myridium** [comment]
Image

**Comment by spwhitton** [comment]
Hello,

On Tue 23 Nov 2021 at 02:05PM -08, Myridium wrote:

>> Hello,
>> On Sun 21 Nov 2021 at 03:31PM -08, Myridium wrote: So this configuration option resolves this very serious long-standing bug... and you've opted to turn the option off by default? I don't understand.
>> I don't consider the bug resolved. The option simply raises awareness of it.
>> […](#)
>> -- Sean Whitton
>
> Hi Sean,
>
> Sorry I'm a bit confused about what exactly this pull request resolves. Could you please clarify what exactly this option does?
>
> Yesterday I tested your library and I found that my remote gcrypt server rejected my fast-forward push because it had commits which I did not have locally.
>
> Isn't the big in your program supposed to be that this does *not* happen?
>
> This was before I configured any git config.

Please see the mailing list archives and post there not here per
CONTRIBUTING.rst.  Thanks.

-- 
Sean Whitton

**Pull request closed without merging**
